name: frute
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider: ^2.0.0
  mapbox_search_flutter: ^1.0.3
  cloud_firestore: ^0.13.6
  geoflutterfire: ^2.1.0
  rxdart: ^0.23.1
  location: ^3.0.0
  firebase_messaging: ^6.0.16
  shared_preferences: ^0.5.7+3
  http: ^0.12.1
  google_directions_api: ^0.5.0
  flutter_polyline_points: ^0.2.1
  google_maps_flutter: ^0.5.28+1
  angles: ^1.2.1
  firebase_auth: ^0.16.1
  intl_phone_number_input: ^0.4.5
  pin_code_fields: ^3.1.2
  cached_network_image: ^2.2.0+1
  rating_bar: ^0.2.0
  flutter_svg: ^0.17.4
  page_transition: ^1.1.5
  google_map_location_picker: ^3.3.3
  image_picker: ^0.6.7+2
  image_cropper: ^1.2.3
  permission_handler: ^5.0.0+hotfix.5
  flutter_local_notifications: ^1.4.4+1
  url_launcher: ^5.4.11
  circular_profile_avatar: ^1.0.6
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^2.2.0
  simple_animations: ^2.2.1
  flutter_neumorphic: ^3.0.1
  neumorphic: ^0.3.2
  flutter_xlider: ^3.4.0
  slider_button: ^0.5.0
  flutter_custom_clippers: ^1.1.1
  introduction_screen: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/car_icon.png
    - assets/beetroot.jpg
    - assets/bitterground.jpg
    - assets/brinjal.jpg
    - assets/cabbagesmall.jpg
    - assets/capsicum.jpg
    - assets/capsicumorange.jpg
    - assets/capsicumred.jpg
    - assets/ladiesfinger.jpg
    - assets/mushroom.jpg
    - assets/onion.jpg
    - assets/potato.jpg
    - assets/pumpkingreen.jpg
    - assets/raddish.jpg
    - assets/tomato.jpg
    - assets/locating_anim.gif
    - assets/user.svg
    - assets/bill.svg
    - assets/home.svg
    - assets/home.svg
    - assets/person.png
    - assets/BG-img.png
    - assets/veg_box.jpg
    - assets/medal.svg
    - assets/mapBack.svg
    - assets/truck.svg
    - assets/BG.png
    - assets/marker.svg
    - assets/loading.gif
    - assets/ripple.gif
    - assets/waiting_animation.gif
    - assets/HL.png
    - assets/coming_soon.svg
    - assets/coming_soon2.svg
    - assets/coming_soon2.png
    - assets/slide3.svg
    - assets/slide2.svg
    - assets/slide1.svg
    - assets/slide3.png
    - assets/slide2.png
    - assets/slide1.png
    - assets/comingsoon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Italic.ttf
        - asset: fonts/Ubuntu-BoldItalic.ttf
        - asset: fonts/Ubuntu-Bold.ttf
        - asset: fonts/Ubuntu-Light.ttf
        - asset: fonts/Ubuntu-LightItalic.ttf
        - asset: fonts/Ubuntu-Medium.ttf
        - asset: fonts/Ubuntu-MediumItalic.ttf
          weight: 400
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
