import 'vegetable.dart';

List<Vegetable> vegetables = [
  Vegetable('Potato', imageUrl: 'assets/potato.jpg'),
  Vegetable('Onion', imageUrl: 'assets/onion.jpg'),
  Vegetable('Ginger', imageUrl: 'assets/ginger.jpg'),
  Vegetable('Garlic', imageUrl: 'assets/garlic.jpg'),
  Vegetable('Chilli', imageUrl: 'assets/chilli.jpg'),
  Vegetable('Coriander/Dhaniya', imageUrl: 'assets/dhaniya.jpg'),
  Vegetable('Lime and Lemon', imageUrl: 'assets/lemon.jpg'),
  Vegetable('Tomato', imageUrl: 'assets/tomato.jpg'),
  Vegetable('Brinjal', imageUrl: 'assets/brinjal.jpg'),
  Vegetable('Bhindi/Okra', imageUrl: 'assets/bhindi.jpg'),
  Vegetable('Cabbage/Patta Gobi', imageUrl: 'assets/cabbage.jpg'),
  Vegetable('Cauliflower/Phool Gobi', imageUrl: 'assets/cauliflower.jpg'),
  Vegetable('Carrot', imageUrl: 'assets/carrot.jpg'),
  Vegetable('Pumpkin', imageUrl: 'assets/pumpkin.jpg'),
  Vegetable('Lauki/Bottle Gourd', imageUrl: 'assets/gourd.jpg'),
  Vegetable('Radish', imageUrl: 'assets/radish.jpg'),
  Vegetable('Imli', imageUrl: 'assets/imli.jpg'),
  Vegetable('Cucumber/Kheera', imageUrl: 'assets/cucumber.jpg'),
  Vegetable('Cucumber/Kakdi', imageUrl: 'assets/kakdi.jpg'),
  Vegetable('Mint Leaves', imageUrl: 'assets/mint.jpg'),
  Vegetable('Green Banana/Kaccha Kela', imageUrl: 'assets/greenbanana.jpg'),
  Vegetable('Methi', imageUrl: 'assets/methi.jpg'),
  Vegetable('Parwal', imageUrl: 'assets/parwal.jpg'),
  Vegetable('Kathal/Jackfruit', imageUrl: 'assets/kathal.jpg'),
  Vegetable('Green Mango/Kaccha Aam', imageUrl: 'assets/rawmango.jpg'),
  Vegetable('Arbi', imageUrl: 'assets/arbi.jpg'),
  Vegetable('Tinda', imageUrl: 'assets/tinda.jpg'),
  Vegetable('Drumsticks', imageUrl: 'assets/drumsticks.jpg'),
  Vegetable('Amla', imageUrl: 'assets/amla.jpg'),
  Vegetable('Bitter Gourd/Karela', imageUrl: 'assets/bittergourd.jpg'),
  Vegetable('Green Beans', imageUrl: 'assets/greenbeans.jpeg'),
  Vegetable('Green Peas/Hari Matar', imageUrl: 'assets/greenpeas.jpg'),
  Vegetable('Capsicum', imageUrl: 'assets/capsicum.jpg'),
  Vegetable('Spinach', imageUrl: 'assets/spinach.jpg'),
  Vegetable('Turnip/Shalgam', imageUrl: 'assets/turnip.jpg'),
  Vegetable('Beet', imageUrl: 'assets/beet.jpg'),
  Vegetable('Kundru', imageUrl: 'assets/kundru.jpeg'),
  Vegetable('Broccoli', imageUrl: 'assets/broccoli.jpg'),
  Vegetable('Corn/Baby Corn', imageUrl: 'assets/corn.jpg'),
  Vegetable('Spring Onion', imageUrl: 'assets/springonion.jpg'),
  Vegetable('Mushrooms', imageUrl: 'assets/mushroom.jpg'),
  Vegetable('Kiwi', imageUrl: 'assets/kiwi.jpg'),
  Vegetable('Curry Leaves', imageUrl: 'assets/curryleaves.jpg'),
  Vegetable('Torai/Ridge Gourd', imageUrl: 'assets/tori.jpg'),
];
